import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { ImagePickerAsset } from 'expo-image-picker';
import { newIdempotencyKey, request } from '@/api/client';
import type { Money } from '@/api/money';
import { duesKeys } from '@/features/dues/queries';

export type PaymentDocument = {
  index: number;
  original_name: string;
  mime: string | null;
  size: number | null;
  uploaded_at: string | null;
};

export type PaymentItem = {
  fee_assign_id: number;
  period: string;
  instalment_amount: Money;
  fine_amount: Money;
};

export type Payment = {
  id: number;
  invoice_no: string;
  status: 'pending' | 'completed' | 'suspended' | 'expired';
  payment_type: 'manual' | 'online';
  /**
   * Whether this payment ever reached the gateway.
   *
   * False on an online payment means the session call failed — the row exists,
   * nothing was sent, and nobody is waiting on a bank. The two look identical
   * to a member and are not.
   */
  gateway_started?: boolean;
  /** Instalments ONLY. Never includes a fine. */
  payable_amount: Money;
  fine_amount: Money;
  total_amount: Money;
  payment_date: string | null;
  expires_at: string | null;
  documents: PaymentDocument[];
  items?: PaymentItem[];
};

export const paymentKeys = {
  all: ['payments'] as const,
  detail: (id: number) => ['payments', id] as const,
};

export function usePayments() {
  return useQuery({
    queryKey: paymentKeys.all,
    queryFn: async () => (await request<{ data: Payment[] }>('/payments')).data,
  });
}

/**
 * One payment, polled while it is still pending.
 *
 * THE APP NEVER DECIDES THAT A PAYMENT SUCCEEDED. The member's return from the
 * gateway is not evidence — they can close the tab before it happens, or reach
 * it without having paid — so the answer comes from asking the server, which
 * asks the gateway. This is the polling half of that (ADR-0007); the other half
 * is the gateway's own callback, which usually gets there first.
 *
 * Polling stops the moment the payment is not pending, so a completed payment
 * costs one request and a settled screen makes no traffic at all.
 */
export function usePayment(id: number, options: { poll?: boolean } = {}) {
  return useQuery({
    queryKey: paymentKeys.detail(id),
    queryFn: async () => (await request<{ data: Payment }>(`/payments/${id}`)).data,
    refetchInterval: (query) =>
      options.poll && query.state.data?.status === 'pending' ? 4000 : false,
  });
}

/**
 * Ask the server for a hosted payment page.
 *
 * A SEPARATE CALL FROM CREATING THE PAYMENT, deliberately. The row exists
 * first, so a member whose phone dies between the two leaves a reconcilable
 * pending payment rather than money taken at the bank against nothing at all —
 * which is exactly defect D-9 in the legacy flow (FR-PAY-7).
 *
 * Not a `useQuery`: asking for a session is a side effect with a lifetime, and
 * one refetched in the background would hand the member a second live session
 * for the same invoice.
 */
export function useGatewaySession() {
  return useMutation({
    mutationFn: async (paymentId: number) =>
      (
        await request<{ data: { url: string; reference: string; expires_at: string | null } }>(
          `/payments/${paymentId}/gateway-session`,
          { method: 'POST' },
        )
      ).data,
  });
}

/**
 * Create a payment intent — manual with a bank slip, or online.
 *
 * THE IDEMPOTENCY KEY IS GENERATED ONCE PER ATTEMPT, NOT PER REQUEST.
 * -------------------------------------------------------------------
 * It is created when the member taps Pay and held in `attemptKey` for the life
 * of that attempt. If the submission times out and the member taps again, the
 * SAME key goes up, and the server returns the original payment instead of
 * creating a second one.
 *
 * A fresh key per retry would defeat the entire mechanism and produce exactly
 * the duplicate charges the legacy system's audit report exists to find. This
 * is also why mutations never auto-retry (see the QueryClient config).
 */
export function useCreatePayment() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (input: {
      feeAssignIds: number[];
      documents: ImagePickerAsset[];
      /** Generated by the screen when the attempt starts, reused on retry. */
      attemptKey: string;
      /**
       * `manual` carries a bank slip and waits for staff to approve it;
       * `online` carries nothing and waits for the gateway. Defaulted so every
       * existing caller keeps the behaviour it had.
       */
      type?: 'manual' | 'online';
    }) => {
      const form = new FormData();

      input.feeAssignIds.forEach((id) => form.append('fee_assign_ids[]', String(id)));
      form.append('payment_type', input.type ?? 'manual');

      input.documents.forEach((asset, index) => {
        form.append('documents[]', {
          uri: asset.uri,
          name: asset.fileName ?? `slip-${index + 1}.jpg`,
          type: asset.mimeType ?? 'image/jpeg',
        } as unknown as Blob);
      });

      const response = await request<{ data: Payment }>('/payments', {
        method: 'POST',
        formData: form,
        idempotencyKey: input.attemptKey,
      });

      return response.data;
    },

    onSuccess: () => {
      // The paid instalments have moved to Requested, so both lists are stale.
      queryClient.invalidateQueries({ queryKey: duesKeys.all });
      queryClient.invalidateQueries({ queryKey: paymentKeys.all });
    },
  });
}

/** A key for one payment attempt. Call once when the attempt begins. */
export function startAttempt(): string {
  return newIdempotencyKey();
}
