import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { ImagePickerAsset } from 'expo-image-picker';
import { newIdempotencyKey, request } from '@/api/client';
import type { Money } from '@/api/money';
import { duesKeys } from '@/features/dues/queries';

export type PaymentDocument = {
  index: number;
  original_name: string;
  mime: string | null;
  size: number | null;
  uploaded_at: string | null;
};

export type PaymentItem = {
  fee_assign_id: number;
  period: string;
  instalment_amount: Money;
  fine_amount: Money;
};

export type Payment = {
  id: number;
  invoice_no: string;
  status: 'pending' | 'completed' | 'suspended' | 'expired';
  payment_type: 'manual' | 'online';
  /** Instalments ONLY. Never includes a fine. */
  payable_amount: Money;
  fine_amount: Money;
  total_amount: Money;
  payment_date: string | null;
  expires_at: string | null;
  documents: PaymentDocument[];
  items?: PaymentItem[];
};

export const paymentKeys = {
  all: ['payments'] as const,
  detail: (id: number) => ['payments', id] as const,
};

export function usePayments() {
  return useQuery({
    queryKey: paymentKeys.all,
    queryFn: async () => (await request<{ data: Payment[] }>('/payments')).data,
  });
}

export function usePayment(id: number) {
  return useQuery({
    queryKey: paymentKeys.detail(id),
    queryFn: async () => (await request<{ data: Payment }>(`/payments/${id}`)).data,
  });
}

/**
 * Create a manual payment with proof of payment attached.
 *
 * THE IDEMPOTENCY KEY IS GENERATED ONCE PER ATTEMPT, NOT PER REQUEST.
 * -------------------------------------------------------------------
 * It is created when the member taps Pay and held in `attemptKey` for the life
 * of that attempt. If the submission times out and the member taps again, the
 * SAME key goes up, and the server returns the original payment instead of
 * creating a second one.
 *
 * A fresh key per retry would defeat the entire mechanism and produce exactly
 * the duplicate charges the legacy system's audit report exists to find. This
 * is also why mutations never auto-retry (see the QueryClient config).
 */
export function useCreatePayment() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (input: {
      feeAssignIds: number[];
      documents: ImagePickerAsset[];
      /** Generated by the screen when the attempt starts, reused on retry. */
      attemptKey: string;
    }) => {
      const form = new FormData();

      input.feeAssignIds.forEach((id) => form.append('fee_assign_ids[]', String(id)));
      form.append('payment_type', 'manual');

      input.documents.forEach((asset, index) => {
        form.append('documents[]', {
          uri: asset.uri,
          name: asset.fileName ?? `slip-${index + 1}.jpg`,
          type: asset.mimeType ?? 'image/jpeg',
        } as unknown as Blob);
      });

      const response = await request<{ data: Payment }>('/payments', {
        method: 'POST',
        formData: form,
        idempotencyKey: input.attemptKey,
      });

      return response.data;
    },

    onSuccess: () => {
      // The paid instalments have moved to Requested, so both lists are stale.
      queryClient.invalidateQueries({ queryKey: duesKeys.all });
      queryClient.invalidateQueries({ queryKey: paymentKeys.all });
    },
  });
}

/** A key for one payment attempt. Call once when the attempt begins. */
export function startAttempt(): string {
  return newIdempotencyKey();
}
